name = "ca-ed-code-mcp"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# KV Namespaces
# Note: You'll need to create these with:
# wrangler kv:namespace create "CACHE"
# wrangler kv:namespace create "RATE_LIMIT"
# Then update the IDs below

[[kv_namespaces]]
binding = "CACHE"
id = "YOUR_CACHE_KV_ID"

[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "YOUR_RATE_LIMIT_KV_ID"

[vars]
CACHE_TTL = "86400"
GLOBAL_RATE_LIMIT = "1000"
SECTION_RATE_LIMIT = "10"
RATE_LIMIT_WINDOW = "60"
LOG_LEVEL = "info"

# Development environment
[env.dev]
vars = { LOG_LEVEL = "debug" }

# Production environment
[env.production]
routes = [
  { pattern = "ca-ed-code.workers.dev/*", zone_name = "" }
]